name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
        tag_suffix: " (beta)"
        changelog_structure: "**{{messageHeadline}}** {{author}}\n"
        version: "${{ steps.previous_step.outputs.version }}"